Map<String, List<String>> symptomToService = {
  'itching': ['Dermatology'],
  'skin_rash': ['Dermatology'],
  'continuous_sneezing': ['Allergy', 'Pulmonology'],
  'shivering': ['General Medicine'],
  'stomach_pain': ['Gastroenterology', 'General Surgery'],
  'acidity': ['Gastroenterology'],
  'vomiting': ['Gastroenterology', 'General Medicine'],
  'indigestion': ['Gastroenterology'],
  'muscle_wasting': ['Neurology', 'Orthopedics'],
  'patches_in_throat': ['ENT', 'General Medicine'],
  'fatigue': ['General Medicine', 'Endocrinology'],
  'weight_loss': ['Endocrinology', 'Oncology'],
  'sunken_eyes': ['General Medicine', 'Nephrology'],
  'cough': ['Pulmonology', 'ENT'],
  'headache': ['Neurology'],
  'chest_pain': ['Cardiology', 'Pulmonology'],
  'back_pain': ['Orthopedics', 'General Medicine'],
  'weakness_in_limbs': ['Neurology', 'Orthopedics'],
  'chills': ['Infectious Diseases', 'General Medicine'],
  'joint_pain': ['Rheumatology', 'Orthopedics'],
  'yellowish_skin': ['Hepatology', 'Dermatology'],
  'constipation': ['Gastroenterology'],
  'pain_during_bowel_movements': ['Gastroenterology'],
  'breathlessness': ['Pulmonology', 'Cardiology'],
  'cramps': ['Gynecology', 'General Medicine'],
  'weight_gain': ['Endocrinology'],
  'mood_swings': ['Psychiatry', 'Endocrinology'],
  'neck_pain': ['Orthopedics', 'Neurology'],
  'muscle_weakness': ['Neurology', 'Orthopedics'],
  'stiff_neck': ['Neurology', 'General Medicine'],
  'pus_filled_pimples': ['Dermatology'],
  'burning_micturition': ['Urology', 'Nephrology'],
  'bladder_discomfort': ['Urology'],
  'high_fever': ['Infectious Diseases', 'General Medicine'],
  'nodal_skin_eruptions': ['Dermatology', 'Infectious Diseases'],
  'ulcers_on_tongue': ['ENT', 'General Medicine'],
  'loss_of_appetite': ['Gastroenterology', 'Endocrinology'],
  'restlessness': ['Psychiatry', 'Neurology'],
  'dehydration': ['General Medicine'],
  'dizziness': ['Neurology', 'Cardiology'],
  'weakness_of_one_body_side': ['Neurology'],
  'lethargy': ['Endocrinology', 'General Medicine'],
  'nausea': ['Gastroenterology', 'General Medicine'],
  'abdominal_pain': ['Gastroenterology', 'General Surgery'],
  'pain_in_anal_region': ['Gastroenterology', 'Proctology'],
  'sweating': ['General Medicine', 'Endocrinology'],
  'bruising': ['Hematology'],
  'cold_hands_and_feets': ['Cardiology', 'Neurology'],
  'anxiety': ['Psychiatry'],
  'knee_pain': ['Orthopedics'],
  'swelling_joints': ['Rheumatology', 'Orthopedics'],
  'blackheads': ['Dermatology'],
  'foul_smell_of_urine': ['Urology'],
  'skin_peeling': ['Dermatology'],
  'blister': ['Dermatology'],
  'dischromic_patches': ['Dermatology'],
  'watering_from_eyes': ['Ophthalmology', 'ENT'],
  'extra_marital_contacts': ['Gynecology'],
  'diarrhoea': ['Gastroenterology', 'Infectious Diseases'],
  'loss_of_balance': ['Neurology', 'General Medicine'],
  'blurred_and_distorted_vision': ['Ophthalmology'],
  'altered_sensorium': ['Neurology', 'Psychiatry'],
  'dark_urine': ['Hepatology', 'Nephrology'],
  'swelling_of_stomach': ['Gastroenterology', 'General Surgery'],
  'bloody_stool': ['Gastroenterology', 'General Surgery'],
  'obesity': ['Endocrinology', 'Nutrition'],
  'hip_joint_pain': ['Orthopedics'],
  'movement_stiffness': ['Neurology', 'Orthopedics'],
  'spinning_movements': ['Neurology'],
  'scurring': ['Dermatology'],
  'continuous_feel_of_urine': ['Urology'],
  'silver_like_dusting': ['Dermatology'],
  'red_sore_around_nose': ['Dermatology'],
  'spotting_urination': ['Urology'],
  'passage_of_gases': ['Gastroenterology'],
  'irregular_sugar_level': ['Endocrinology'],
  'family_history': ['General Medicine'],
  'lack_of_concentration': ['Psychiatry', 'Neurology'],
  'excessive_hunger': ['Endocrinology'],
  'yellowing_of_eyes': ['Hepatology'],
  'distention_of_abdomen': ['Gastroenterology'],
  'irritation_in_anus': ['Gastroenterology'],
  'swollen_legs': ['Cardiology', 'Nephrology'],
  'painful_walking': ['Orthopedics'],
  'small_dents_in_nails': ['Dermatology'],
  'yellow_crust_ooze': ['Dermatology'],
  'internal_itching': ['Dermatology'],
  'mucoid_sputum': ['Pulmonology'],
  'history_of_alcohol_consumption': ['Hepatology', 'General Medicine'],
  'swollen_blood_vessels': ['Cardiology'],
  'unsteadiness': ['Neurology', 'General Medicine'],
  'inflammatory_nails': ['Dermatology'],
  'depression': ['Psychiatry'],
  'fluid_overload': ['Nephrology'],
  'swelled_lymph_nodes': ['Oncology', 'Infectious Diseases'],
  'malaise': ['General Medicine'],
  'prominent_veins_on_calf': ['Vascular Surgery'],
  'puffy_face_and_eyes': ['Nephrology'],
  'fast_heart_rate': ['Cardiology'],
  'irritability': ['Psychiatry', 'Neurology'],
  'muscle_pain': ['Orthopedics', 'General Medicine'],
  'mild_fever': ['General Medicine'],
  'yellow_urine': ['Hepatology'],
  'phlegm': ['Pulmonology'],
  'enlarged_thyroid': ['Endocrinology'],
  'increased_appetite': ['Endocrinology'],
  'visual_disturbances': ['Ophthalmology', 'Neurology'],
  'brittle_nails': ['Dermatology'],
  'drying_and_tingling_lips': ['Dermatology'],
  'polyuria': ['Endocrinology'],
  'pain_behind_the_eyes': ['Ophthalmology'],
  'toxic_look_(typhos)': ['Infectious Diseases'],
  'throat_irritation': ['ENT'],
  'swollen_extremeties': ['Cardiology', 'Nephrology'],
  'slurred_speech': ['Neurology'],
  'red_spots_over_body': ['Dermatology'],
  'belly_pain': ['Gastroenterology'],
  'receiving_blood_transfusion': ['Hematology'],
  'acute_liver_failure': ['Hepatology'],
  'redness_of_eyes': ['Ophthalmology'],
  'rusty_sputum': ['Pulmonology'],
  'abnormal_menstruation': ['Gynecology'],
  'receiving_unsterile_injections': ['Infectious Diseases'],
  'coma': ['Neurology'],
  'sinus_pressure': ['ENT'],
  'palpitations': ['Cardiology'],
  'stomach_bleeding': ['Gastroenterology'],
  'runny_nose': ['ENT'],
  'congestion': ['ENT'],
  'blood_in_sputum': ['Pulmonology'],
  'loss_of_smell': ['ENT'],
};
